Introduce value resolver for auto-injecting `PendingDocuments` from request object
kbond/document-library pull request #4
Opened 2022-12-06 14:01 UTC by Lustmored

As usual this is a proof of concept at first. If I get a green light I will work on the tests and docs for this code.

I have created a simple demo application to show the idea behind this PR: https://github.com/Lustmored/document-demo .

The idea is to simply be able to inject `PendingDocument` directly into controllers (and components when it comes to that), so that this controller boilerplate code:
```
public function __invoke(Request $request): Response
    {
        $file = null;
        if ($request->files->has('file')) {
            $file = new PendingDocument($request->files->get('file'));
        }
        // Do things with $file
    }
```
Can be simplified to:
```
public function __invoke(?PendingDocument $file): Response
    {
        // Do things with $file
    }
```

I have managed to do that by implementing `ValueResolverInterface` and letting Symfony `http-kernel` do the rest.

In addition to that simple case I've also introduced `RequestFilesExtractor` service. It contains a single helper method that extract file/-s from request based on provided path. In conjunction with `UploadedFile` attribute it can be used to specify the path (from nested forms, like "data[file]") and extract file/-s for injecting. It allows seamless injections like that:

```
public function __invoke(
        #[UploadedFile('data[file]')]
        ?PendingDocument $file
    ): Response {
        // Do things with $file
    }
```
or even multiple files:
```
public function __invoke(
        #[UploadedFile('data[file]')]
        array $files = []
    ): Response {
        // Do something with files - it can be an empty array or an array of PendingDocuments
    }
```

I would love to get feedback and polish this first. I'm convinced that `RequestFilesExtractor` will come in very handy when it will comes to wiring things into live components, so let's do one step at a time :)

2022-12-06 15:01 UTC, Lustmored commented
I just noted that my resolver would inject anything typed with `array`. I will try to handle that case better tomorrow.

2022-12-06 21:33 UTC, kbond reviewed
Love this, what a great feature!

2022-12-06 21:33 UTC, kbond commented on src/Document/Library/Bridge/Symfony/ValueResolver/PendingDocumentValueResolver.php
> +namespace Zenstruck\Document\Library\Bridge\Symfony\ValueResolver;
```suggestion
namespace Zenstruck\Document\Library\Bridge\Symfony\HttpKernel;
```

2022-12-06 21:33 UTC, kbond commented on src/Document/Library/Bridge/Symfony/ValueResolver/RequestFilesExtractor.php
> +namespace Zenstruck\Document\Library\Bridge\Symfony\ValueResolver;
```suggestion
namespace Zenstruck\Document\Library\Bridge\Symfony\HttpKernel;
```

2022-12-06 21:33 UTC, kbond commented on src/Document/Library/Bridge/Symfony/ValueResolver/UploadedFile.php
> +namespace Zenstruck\Document\Library\Bridge\Symfony\ValueResolver;
```suggestion
namespace Zenstruck\Document\Library\Bridge\Symfony\Attribute;
```

Although, this doesn't have to be symfony-specific so maybe:

```suggestion
namespace Zenstruck\Document\Attribute;
```

2022-12-06 21:33 UTC, kbond commented on src/Document/Library/Bridge/Symfony/ValueResolver/RequestFilesExtractor.php
> +        $this->propertyAccessor = new PropertyAccessor(
Why not injected?

2022-12-06 21:35 UTC, kbond commented
> I just noted that my resolver would inject anything typed with array.

Yeah, unfortunately `ArgumentMetadata` doesn't use the property-info component which would allow us to determine the array type. Maybe we'll need to require the attribute for an array or do you have something else in mind?

2022-12-06 21:47 UTC, kbond commented on src/Document/Library/Bridge/Symfony/ValueResolver/RequestFilesExtractor.php
> +    private function canonizePath(string $path): string
I really wish property-access supported _dot_ notation for both arrays and objects... `data.file` is nicer imo.

I actually built my own dot notation system in [this library](https://github.com/kbond/document-library/blob/9a5c7594b630c8b671ee26a950362f1ebaea832b/src/Document/Namer/ExpressionNamer.php#L72). Maybe we should reuse?

What do you think about moving the dot access functionality to `Expression`:

```php
$expression = new Expression($path);
$files = $expression->access($request->files->all());
```

2022-12-07 09:42 UTC, Lustmored commented
> Yeah, unfortunately `ArgumentMetadata` doesn't use the property-info component which would allow us to determine the array type. Maybe we'll need to require the attribute for an array or do you have something else in mind?

This is exactly my approach. I am changing it to require either `PendingDocument` typehint (with optional attribute) for a single file, or require an attribute for multiple files. In the second case an array is always injected (but can be empty), so that consumers can use whatever typehint they want (`array` or `iterable` or probably others compatible with an array)

2022-12-07 09:58 UTC, Lustmored commented on src/Document/Library/Bridge/Symfony/ValueResolver/RequestFilesExtractor.php
> +        $this->propertyAccessor = new PropertyAccessor(
Probably wasn't thinking enough ;)

2022-12-07 10:05 UTC, Lustmored commented on src/Document/Library/Bridge/Symfony/ValueResolver/RequestFilesExtractor.php
> +    private function canonizePath(string $path): string
It is nicer and from purely backend developer perspective it would probably make more sense.

My reasoning here is more "fullstack centered", where the path to the uploaded file can be exactly the same as `name` property of `<input type="file" />`. I think it is easier to maintain exactly the same string in two places instead of changing it into two formats (HTML one and "backend" one), so that:

`<input type="file" name="file" />` -> `PendingFile $file`
`<input type="file" name="form[data][file]" />` -> `#[UploadedFile('form[data][file]') PendingFile $file`
`<input type="file" name="form[files][]" multiple />` -> `#[UploadedFile('form[files][]') array $files`
(the last one I've added in recent commit)

I believe it makes the work much easier, as copying `name` attribute from HTML into backend requires no knowledge about any syntax that is actually used.

2022-12-07 10:08 UTC, Lustmored commented
@kbond I'm glad you like my ideas here :smile: I have refactored namespaces and fixed a few tiny bits. I have updated the demo if you want to play with it. I should manage to work on docs and tests sometime next week to get this merged and then will start tinkering with live-components and this library. And I think there are just a few tiny pieces I will have to work on as most is already looking great :smile:

2022-12-07 13:22 UTC, kbond commented on src/Document/Library/Bridge/Symfony/ValueResolver/RequestFilesExtractor.php
> +    private function canonizePath(string $path): string
You're right, let's leave as is!

2022-12-07 13:30 UTC, kbond commented
FYI, a rebase should fix the CI

2022-12-13 13:05 UTC, Lustmored commented
@kbond I have added tests and a README section. Harsh review is very welcome as tests and docs are my weaknesses :wink: 

Please also approve the workflow. I will then work on code style as it's probably way off - I don't care about it much when writing code and let the tools do their job later on.

2022-12-13 14:50 UTC, kbond requested changes

2022-12-13 14:50 UTC, kbond commented on README.md
> +```
I think we can remove this section.

2022-12-13 14:50 UTC, kbond commented on README.md
> +and injects `PendingDocument` directly, so below examples are handled:
```suggestion
An argument value resolver is provided that enables injecting `PendingDocument`'s
(from `$request->files`) directly into your controllers:
```

2022-12-13 14:50 UTC, kbond commented on README.md
> +    ): Response {
```suggestion
    public function __invoke(
        // Inject directly from $request->files->get('file')
        ?PendingDocument $file,

        // Inject by path, which is the same format as `name` on HTML `<input>`
        #[UploadedFile('data[file]')]
        ?PendingDocument $anotherFile,

        // Inject array of pending documents from $request->files->get('files')
        #[UploadedFile]
        array $files,

        // Inject array of pending documents by path
        #[UploadedFile('data[files]')]
        array $anotherFiles
    ): Response {
```

2022-12-13 14:50 UTC, kbond commented on src/Document/Library/Bridge/Symfony/DependencyInjection/ZenstruckDocumentLibraryExtension.php
> +        ;
```suggestion
            ->addArgument(new Reference('property_accessor'))
        ;
```

Until a time where the default `property_accessor` causes a problem.

2022-12-13 14:50 UTC, kbond commented on src/Document/Library/Bridge/Symfony/HttpKernel/PendingDocumentValueResolver.php
> +    public function __construct(
I think this should be a service locator to avoid having to instantiate `RequestFilesExtractor` on every request. Don't worry about it for this PR if you haven't created one of these before - we can make a perf optimization PR later.

2022-12-13 14:50 UTC, kbond commented on tests/Bridge/Symfony/Fixture/Controller/NoInjectionController.php
> +class NoInjectionController extends AbstractController
What do you think about having just a `ArgumentResolverController` with methods for each of the different scenario?

2022-12-13 14:50 UTC, kbond commented on tests/Bridge/Symfony/HttpKernel/PendingDocumentValueResolverTest.php
> +class PendingDocumentValueResolverTest extends TestCase
Let's make this a functional `KernelTestCase` so we can test that it's wired up in Symfony correctly at the same time.

I think this will fix the deprecations too.

2022-12-13 14:55 UTC, kbond commented
A bit annoying but I think [this is the only way](https://github.com/EasyCorp/EasyAdminBundle/blob/4.x/src/ArgumentResolver/AdminContextResolver.php) to fix the deprecation problem.

2022-12-13 14:57 UTC, Lustmored commented
Thank you for the review. I was literally writing about the deprecation problem when you've shared a (dirty, but valid) solution - I think it can get simpler by introducing a common trait. I will work on that, and other very insightful review tomorrow :+1:

2022-12-14 10:49 UTC, Lustmored commented
I think I have addressed everything by now. I'm uncertain if what I've done with the test (I had to introduce public alias to the service in `TestKernel`), so please double-check if that's correct now.

I think it might be worth writing some tests which actually mock full request lifecycle. But on the other hand that might be an overkill as those are literally two methods, both of which have (hopefully) all cases tested already. WDYT?

As a side note: If I understand correctly, the codecov failure comes from the hack on interface deprecation.

2022-12-14 16:29 UTC, kbond requested changes

2022-12-14 16:29 UTC, kbond commented on src/Document/Library/Bridge/Symfony/DependencyInjection/ZenstruckDocumentLibraryExtension.php
> +        $container->register(RequestFilesExtractor::class)
```suggestion
        $container->register('.zenstruck_document.value_resolver.request_files_extractor', RequestFilesExtractor::class)
```

(otherwise this service will be autoloadable.

2022-12-14 16:29 UTC, kbond commented on src/Document/Library/Bridge/Symfony/DependencyInjection/ZenstruckDocumentLibraryExtension.php
> +                    RequestFilesExtractor::class => new Reference(RequestFilesExtractor::class),
```suggestion
                    RequestFilesExtractor::class => new Reference('.zenstruck_document.value_resolver.request_files_extractor'),
```

2022-12-14 16:29 UTC, kbond commented on tests/Bridge/Symfony/HttpKernel/PendingDocumentValueResolverTest.php
> +class PendingDocumentValueResolverTest extends KernelTestCase
Sorry, I should have been more clear. I meant that this test should use the test client to actually make requests to `ArgumentResolverController` (needs routing configured).

2022-12-14 16:31 UTC, kbond commented
> As a side note: If I understand correctly, the codecov failure comes from the hack on interface deprecation.

Yep, no worries about that.

> I think it might be worth writing some tests which actually mock full request lifecycle.

As I mentioned in my review, I'd prefer real functional tests using the test client. This will test the full lifecycle.

2022-12-14 16:34 UTC, kbond commented
You can see something similar that I did here: https://github.com/zenstruck/uri/tree/2.x/tests/Bridge/Symfony/Fixture

- https://github.com/zenstruck/uri/blob/67a1d61305d6322628c38bd204f5f61c276bc8d5/tests/Bridge/Symfony/Fixture/TestKernel.php#L52
- https://github.com/zenstruck/uri/blob/2.x/tests/Bridge/Symfony/FunctionalTest.php

2022-12-15 10:17 UTC, Lustmored commented
I think those tests are much cleaner and more complete now. Thanks for the examples, they were very helpful!

2022-12-15 13:49 UTC, kbond approved these changes
Thanks @Lustmored , great feature!

2022-12-15 13:50 UTC, merged